"""Exceptions: an administrator lets one exact file through, whatever found it.

A false positive is the case this exists for: an engine flags a file the
institution knows to be harmless, and a user needs it. An exception names the
file by its SHA-256 only (never a name or an extension), carries a required
reason, applies to every client or to one, may expire, and is revoked rather
than deleted so the audit trail keeps it.

An exception is looked up once, when a file is accepted, and frozen in the
scan's routing snapshot like every other routing fact: engines still run and
their results are recorded as evidence, but the decision is "Allowed by
exception" whatever they, a profile rule or an archive check said, and no
detection notification is raised. Scans accepted before the exception keep
their decision; the file passes the next time it is sent. A client-scoped
exception wins over a global one for that client.
"""
from __future__ import annotations

import json
import re
import time
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator

from app import database as db
from app.services.decisions import ScanDecision

SHA256 = re.compile(r"^[0-9a-f]{64}$")
MAX_REASON = 500
MAX_DAYS = 3650


class ExceptionCreate(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)
    sha256: str = Field(max_length=128)
    # None: every client, including manual scans.
    service_client_id: int | None = Field(default=None, ge=1, le=9007199254740991)
    reason: str = Field(min_length=1, max_length=MAX_REASON)
    # None: until revoked.
    expires_in_days: int | None = Field(default=None, ge=1, le=MAX_DAYS)

    @field_validator("sha256")
    @classmethod
    def _digest(cls, value: str) -> str:
        cleaned = value.strip().lower()
        if not SHA256.fullmatch(cleaned):
            raise ValueError("Enter the file's full SHA-256 (64 hexadecimal characters).")
        return cleaned

    @field_validator("reason")
    @classmethod
    def _reason(cls, value: str) -> str:
        cleaned = " ".join(value.split())
        if not cleaned:
            raise ValueError("A reason is required.")
        return cleaned


def ensure_schema(connection: Any) -> None:
    id_column = ("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
                 if db.using_postgres() else "id INTEGER PRIMARY KEY AUTOINCREMENT")
    connection.execute(f'''CREATE TABLE IF NOT EXISTS scan_exceptions (
        {id_column},
        sha256 TEXT NOT NULL,
        service_client_id BIGINT REFERENCES service_clients(id),
        reason TEXT NOT NULL,
        created_by TEXT NOT NULL,
        created_at BIGINT NOT NULL,
        expires_at BIGINT,
        revoked_by TEXT,
        revoked_at BIGINT
    )''')
    connection.execute('''CREATE INDEX IF NOT EXISTS idx_scan_exceptions_sha256
        ON scan_exceptions (sha256) WHERE revoked_at IS NULL''')
    connection.execute('''CREATE INDEX IF NOT EXISTS idx_scan_exceptions_seek ON scan_exceptions (id DESC)''')


def active(connection: Any, sha256: str, client_id: int | None, now: int | None = None) -> dict | None:
    """The exception that lets this file through for this client now, if any."""
    current = int(time.time()) if now is None else now
    rows = connection.execute('''SELECT e.id, e.service_client_id, e.reason, e.created_by, e.created_at, e.expires_at
        FROM scan_exceptions e WHERE e.sha256 = ? AND e.revoked_at IS NULL
        AND (e.expires_at IS NULL OR e.expires_at > ?)
        AND (e.service_client_id IS NULL OR e.service_client_id = ?)
        ORDER BY CASE WHEN e.service_client_id IS NULL THEN 1 ELSE 0 END, e.id DESC LIMIT 1''',
        (sha256, current, client_id if client_id is not None else -1)).fetchone()
    if rows is None:
        return None
    return {"id": int(rows["id"]), "scope": "client" if rows["service_client_id"] is not None else "all",
            "reason": str(rows["reason"]), "created_by": str(rows["created_by"]),
            "created_at": int(rows["created_at"]), "expires_at": rows["expires_at"]}


def attach(snapshot_json: str, *, sha256: str, client_id: int | None) -> tuple[str, int | None]:
    """Freeze this file's exception into its snapshot; return the snapshot and the exception id.

    An exception inherited from a parent snapshot (an archive member copies its
    container's) is removed first: an exception names one exact file.
    """
    try:
        snapshot = json.loads(snapshot_json or "{}")
    except (TypeError, json.JSONDecodeError):
        return snapshot_json, None
    if not isinstance(snapshot, dict):
        return snapshot_json, None
    inherited = snapshot.pop("exception", None) is not None
    with db.connect() as connection:
        found = active(connection, sha256, client_id)
    if found is None:
        return (json.dumps(snapshot, separators=(",", ":"), sort_keys=True) if inherited else snapshot_json), None
    snapshot["exception"] = found
    return json.dumps(snapshot, separators=(",", ":"), sort_keys=True), found["id"]


def recorded(snapshot: dict) -> dict | None:
    value = snapshot.get("exception")
    return value if isinstance(value, dict) and isinstance(value.get("id"), int) else None


def apply_exception(decision: ScanDecision, snapshot: dict) -> ScanDecision:
    """An exception allows the file whatever the engines, rules or checks decided."""
    exception = recorded(snapshot)
    if exception is None or decision.action == "wait":
        return decision
    reason = f"Allowed by exception #{exception['id']}: {exception.get('reason', '')}"
    return ScanDecision(action="allow", label="Allow (exception)", tone="warning", confidence="high",
                        policy="exception_allow", reason=reason,
                        reasons=[reason, f"Added by {exception.get('created_by', 'unknown')}.",
                                 f"Without the exception: {decision.label} ({decision.reason})"])


def create(body: ExceptionCreate, created_by: str) -> int:
    now = int(time.time())
    expires = now + body.expires_in_days * 86400 if body.expires_in_days else None
    with db.connect() as connection:
        if body.service_client_id is not None:
            client = connection.execute("SELECT client_key FROM service_clients WHERE id = ?",
                                        (body.service_client_id,)).fetchone()
            if client is None:
                raise LookupError("Service client not found.")
        cursor = connection.execute(f'''INSERT INTO scan_exceptions
            (sha256, service_client_id, reason, created_by, created_at, expires_at)
            VALUES (?, ?, ?, ?, ?, ?) {db.returning_id_clause()}''',
            (body.sha256, body.service_client_id, body.reason, created_by, now, expires))
        return db.require_lastrowid(cursor)


def revoke(exception_id: int, revoked_by: str) -> bool:
    """Revoke an active exception; False when it is missing or already revoked."""
    with db.connect() as connection:
        cursor = connection.execute('''UPDATE scan_exceptions SET revoked_by = ?, revoked_at = ?
            WHERE id = ? AND revoked_at IS NULL''', (revoked_by, int(time.time()), exception_id))
        return int(cursor.rowcount) > 0


class ExceptionItem(BaseModel):
    id: int
    sha256: str
    client_id: int | None
    client_name: str | None
    reason: str
    created_by: str
    created_at: int
    expires_at: int | None
    revoked_by: str | None
    revoked_at: int | None
    state: str
    # Scans this exception let through.
    uses: int


class ExceptionPage(BaseModel):
    items: list[ExceptionItem]
    next_before: int | None


class ExceptionCreated(BaseModel):
    id: int


def page(*, limit: int, before: int | None, state: str, query: str) -> ExceptionPage:
    now = int(time.time())
    conditions, values = [], []
    if before is not None:
        conditions.append("e.id < ?")
        values.append(before)
    if state == "active":
        conditions.append("e.revoked_at IS NULL AND (e.expires_at IS NULL OR e.expires_at > ?)")
        values.append(now)
    elif state == "expired":
        conditions.append("e.revoked_at IS NULL AND e.expires_at IS NOT NULL AND e.expires_at <= ?")
        values.append(now)
    elif state == "revoked":
        conditions.append("e.revoked_at IS NOT NULL")
    term = query.strip().lower()
    if term:
        literal = "%" + term.replace("!", "!!").replace("%", "!%").replace("_", "!_") + "%"
        conditions.append("(e.sha256 LIKE ? ESCAPE '!' OR LOWER(e.reason) LIKE ? ESCAPE '!')")
        values.extend([literal, literal])
    where = ("WHERE " + " AND ".join(conditions)) if conditions else ""
    with db.connect() as connection:
        rows = connection.execute(f'''SELECT e.id, e.sha256, e.service_client_id AS client_id,
            SUBSTR(c.display_name, 1, 100) AS client_name, SUBSTR(e.reason, 1, {MAX_REASON}) AS reason,
            SUBSTR(e.created_by, 1, 100) AS created_by, e.created_at, e.expires_at,
            SUBSTR(e.revoked_by, 1, 100) AS revoked_by, e.revoked_at,
            (SELECT COUNT(*) FROM scan_jobs j WHERE j.exception_id = e.id) AS uses
            FROM scan_exceptions e LEFT JOIN service_clients c ON c.id = e.service_client_id
            {where} ORDER BY e.id DESC LIMIT ?''', (*values, limit + 1)).fetchall()
    items = []
    for row in rows[:limit]:
        values_row = dict(row)
        if values_row["revoked_at"] is not None:
            values_row["state"] = "revoked"
        elif values_row["expires_at"] is not None and int(values_row["expires_at"]) <= now:
            values_row["state"] = "expired"
        else:
            values_row["state"] = "active"
        items.append(ExceptionItem(**values_row))
    return ExceptionPage(items=items, next_before=items[-1].id if len(rows) > limit else None)
