import { test, expect } from '@playwright/test'

test('grouped navigation, worker investigation and compact mobile menu preserve role boundaries', async ({ page }) => {
  await page.goto('dashboard')
  await page.getByLabel('Username', { exact: true }).fill('console-admin')
  await page.getByLabel('Password', { exact: true }).fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const nav = page.getByRole('navigation', { name: 'Workspace' })
  for (const name of ['Operations', 'Integrations', 'Infrastructure', 'Administration']) await expect(nav.getByText(name, { exact: true })).toBeVisible()
  await nav.getByRole('link', { name: 'System', exact: true }).click()
  await expect(page).toHaveURL(/\/system\/overview$/)
  await expect(page.getByRole('heading', { name: 'System overview' })).toBeVisible()
  await page.getByRole('link', { name: 'Open active queue' }).click()
  await page.getByRole('link', { name: 'Acceptance worker', exact: true }).click()
  await expect(page).toHaveURL(/node=console-node/)
  await expect(page.getByRole('dialog')).toContainText('Acceptance worker')
  await expect(page.getByRole('dialog')).toContainText('1970-01-01 00:00:01 UTC')
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await expect(page.getByRole('button', { name: 'Next workers' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Engines', exact: true }).click()
  await expect(page.getByText('Built-in analyzer; no connection check required.')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(nav).toBeHidden()
  const menu = page.getByRole('button', { name: 'Menu', exact: true })
  await menu.click()
  await expect(menu).toHaveAttribute('aria-expanded', 'true')
  await nav.getByRole('link', { name: 'System', exact: true }).click()
  await expect(nav).toBeHidden()
  await expect(page.getByRole('heading', { name: 'System overview' })).toBeVisible()
  await menu.click()
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()
  await expect(menu).toHaveAttribute('aria-expanded', 'false')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/admin-overview-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username', { exact: true }).fill('console-analyst')
  await page.getByLabel('Password', { exact: true }).fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  await menu.click()
  await expect(nav.getByRole('link', { name: 'System', exact: true })).toHaveCount(0)
  await expect(nav.getByRole('link', { name: 'API ledger', exact: true })).toBeVisible()
  await expect(nav.getByRole('link', { name: 'Account', exact: true })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/system/workers')).status()).toBe(403)
})

test('HTTP failures expose a copyable request reference without replay', async ({ page }) => {
  await page.goto('system/overview')
  let attempts = 0
  await page.route('**/api/ui/v1/system/summary', route => {
    attempts++
    return route.fulfill({ status: 503, contentType: 'application/json', headers: { 'X-Request-ID': 'browser-check-42' },
      body: JSON.stringify({ detail: 'Temporary read failure.' }) })
  })
  await page.getByLabel('Username', { exact: true }).fill('console-admin')
  await page.getByLabel('Password', { exact: true }).fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Request ID: browser-check-42')
  await page.getByRole('button', { name: 'Copy request ID' }).click()
  await expect(page.getByRole('button', { name: 'Request ID copied' })).toBeVisible()
  expect(attempts).toBe(1)
})
