import { test, expect } from '@playwright/test'

test('analyst browses API/ICAP history, filters ownership and uses seek pagination', async ({ page }) => {
  await page.goto('api-ledger')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('link', { name: 'ledger-21.bin', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'acceptance-24.bin' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Older scans' }).click()
  await expect(page.getByRole('link', { name: 'ledger-00.bin', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Newest scans' }).click()
  await page.getByRole('combobox', { name: 'Source', exact: true }).selectOption('api')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByRole('link', { name: 'ledger-20.bin', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Filter client #1', exact: true }).first().click()
  await expect(page).toHaveURL(/client_id=1/)
  await page.getByLabel('Client ID', { exact: true }).fill('999999')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByText('No automation scans match these filters.')).toBeVisible()
  await page.getByRole('button', { name: 'Reset filters' }).click()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.getByRole('link', { name: 'ledger-20.bin', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'ledger-21.bin', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await page.getByRole('checkbox').boundingBox())!.width).toBeLessThanOrEqual(20)
  await page.screenshot({ path: '../artifacts/console-e2e/api-ledger-mobile.png', fullPage: true })
})
