import { test, expect } from '@playwright/test'

test('batch overview plus archive direct-child pagination and nested navigation', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('scans/24')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('link', { name: 'Open batch overview' }).click()
  await expect(page.getByRole('heading', { name: 'Batch overview' })).toBeVisible()
  const batchTable = page.getByRole('region', { name: 'Batch scans' })
  await expect(batchTable.getByRole('row')).toHaveCount(21)
  await expect(page.getByLabel('Recorded batch counts').getByText('27')).toBeVisible()
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(batchTable.getByRole('row')).toHaveCount(8)
  await expect(page).toHaveURL(/after_id=44&after_created=/)
  await page.getByRole('button', { name: 'First page', exact: true }).click()
  await batchTable.getByRole('link', { name: 'acceptance-23.bin', exact: true }).click()
  await page.getByRole('link', { name: 'Browse registered direct children' }).click()
  await expect(page.getByRole('heading', { name: 'Archive contents' })).toBeVisible()
  const table = page.getByRole('region', { name: 'Archive child scans' })
  await expect(table.getByRole('row')).toHaveCount(21)
  await page.getByRole('button', { name: 'Next page' }).click()
  await expect(table.getByRole('row')).toHaveCount(6)
  await expect(page).toHaveURL(/after=45&attempt=0/)
  await page.getByRole('button', { name: 'First page', exact: true }).click()
  await expect(table.getByRole('row')).toHaveCount(21)
  await page.getByRole('textbox', { name: 'Search archive paths' }).fill('%_!')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(table.getByRole('row')).toHaveCount(3)
  await expect(table.getByRole('link', { name: 'duplicate%_!.bin', exact: true })).toHaveCount(2)
  await page.screenshot({ path: '../artifacts/console-e2e/archive-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/archive-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Reset', exact: true }).click()
  await page.getByRole('link', { name: 'Browse children of #26' }).click()
  await expect(table.getByRole('row')).toHaveCount(2)
  await expect(page).toHaveURL(/scans\/26\/children/)
  await page.getByRole('link', { name: 'Up one level' }).click()
  await expect(table.getByRole('row')).toHaveCount(21)
  await page.goto('scans/27/children')
  await expect(page.getByRole('heading', { name: 'No registered children on this page' })).toBeVisible()
  await expect(page.getByText(/Lazy extraction may not have run/)).toBeVisible()
  expect(errors).toEqual([])
})
