import { test, expect } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('automation report, full output, batch and protected single deletion', async ({ page }) => {
  await page.goto('api-ledger?q=ledger-21.bin')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('link', { name: 'Open report', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'ledger-21.bin' })).toBeVisible()
  await page.getByRole('link', { name: 'Integration status JSON', exact: true }).click()
  await expect(page.getByLabel('Integration status JSON text')).toContainText('"result_ready": true')
  await expect(page.getByLabel('Integration status JSON text')).toContainText('"queue"')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Back to report' }).click()
  await page.getByRole('link', { name: 'Integration result JSON', exact: true }).click()
  await expect(page.getByLabel('Integration result JSON text')).toContainText('ledger-21.bin')
  await expect(page.getByLabel('Integration result JSON text')).not.toContainText('raw_output')
  await page.getByRole('link', { name: 'Back to report' }).click()
  await page.getByRole('button', { name: 'Show technical output for Static Metadata' }).click()
  await expect(page.getByText('<script>inert automation output</script>', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Full output for Static Metadata' }).click()
  await expect(page.getByLabel('Raw output text', { exact: true })).toContainText('<script>inert automation output</script>')
  await page.getByRole('link', { name: 'Back to report' }).click()
  await page.getByRole('link', { name: 'Open batch overview' }).click()
  await expect(page.getByRole('heading', { name: 'Batch overview' })).toBeVisible()
  for (const kind of ['status', 'result']) {
    await page.getByRole('link', { name: `Batch ${kind} JSON`, exact: true }).click()
    await expect(page.getByLabel(`Batch ${kind} JSON text`)).toContainText('ledger-21.bin')
    await expect(page.getByLabel(`Batch ${kind} JSON text`)).not.toContainText('raw_output')
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    // The complete contract downloads directly, covering batches the inline view refuses.
    const href = await page.getByRole('link', { name: `Download complete ${kind} contract` }).getAttribute('href')
    const served = await page.request.get(href!)
    expect(served.status()).toBe(200)
    expect(served.headers()['content-type']).toContain('application/json')
    expect(served.headers()['content-disposition']).toContain('attachment; filename="masp-batch-')
    const document_ = await served.json()
    expect(Array.isArray(document_.scans)).toBe(true)
    expect(JSON.stringify(document_)).toContain('ledger-21.bin')
    expect(JSON.stringify(document_)).not.toContain('raw_output')
    await page.getByRole('link', { name: 'Back to batch overview' }).click()
  }
  await page.getByRole('link', { name: 'ledger-19.bin', exact: true }).click()
  await page.getByRole('link', { name: 'Browse registered direct children' }).click()
  await expect(page.getByRole('heading', { name: 'Archive contents' })).toBeVisible()
  await page.getByRole('link', { name: /Browse children of #/ }).click()
  await expect(page.getByRole('link', { name: 'inside-auto.txt', exact: true })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: 'Up one level' }).click()
  await expect(page.getByRole('link', { name: 'nested-auto.zip', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Batch overview', exact: true }).click()
  await page.getByRole('link', { name: 'ledger-21.bin', exact: true }).click()
  await page.getByRole('link', { name: 'Scan management', exact: true }).click()
  await expect(page.getByText('Administrator access is required to delete scans.')).toBeVisible()
  for (const [label, extension] of [['Download summary JSON', 'json'], ['Download full CSV', 'csv'], ['Download full JSON', 'json']]) {
    const waiting = page.waitForEvent('download')
    await page.getByRole('button', { name: label, exact: true }).click()
    const download = await waiting
    expect(download.suggestedFilename()).toMatch(new RegExp(`\\.${extension}$`))
    const content = await readFile((await download.path())!, 'utf8')
    expect(content).toContain('ledger-21.bin')
    expect(content).not.toContain('storage_path')
    if (label === 'Download full JSON') expect(content).toContain('<script>inert automation output</script>')
  }

  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Delete scan', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/automation-delete-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Confirm deletion', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('deleted')
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('not found')
})
