import { test, expect } from '@playwright/test'

test('admin reviews fenced routing and analyst is denied', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('link', { name: 'Profile routing' }).click()
  await expect(page.getByRole('heading', { name: 'Acceptance routing' })).toBeVisible()
  const checkbox = page.getByRole('checkbox', { name: /Static Metadata/ })
  await checkbox.uncheck()
  await expect(page.getByRole('button', { name: 'Review engine routing' })).toBeDisabled()
  await checkbox.check()
  await page.getByRole('button', { name: 'Review engine routing' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await checkbox.boundingBox())!.width).toBeLessThanOrEqual(20)
  await page.screenshot({ path: '../artifacts/console-e2e/client-profiles-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Review engine routing' }).click()
  await page.getByRole('button', { name: 'Confirm engine routing' }).click()
  await expect(page.getByText('Profile routing saved. Refresh before editing again.')).toBeVisible()
  await page.reload()
  await expect(checkbox).toBeChecked()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
})
