import { test, expect } from '@playwright/test'

test('admin edits a profile rule list; analyst is denied', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Scan profiles' }).click()
  const rules = page.getByRole('region', { name: 'Rules for Acceptance routing' })
  const rows = rules.getByRole('row')
  await expect(rows).toHaveCount(2)
  await expect(rows.nth(1)).toHaveText('1Every other fileLight check: Static Metadata')
  await expect(rules).toContainText('When the result is not conclusive: Block')
  await page.getByRole('button', { name: 'Edit rules' }).click()
  // The editor replaces the card instead of repeating the profile below it.
  await expect(page.getByRole('button', { name: 'Edit rules' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Add rule' }).click()
  const first = page.getByRole('listitem', { name: 'Rule 1' })
  await first.getByLabel('Larger than (MB)').fill('100')
  await first.getByRole('combobox', { name: 'Action' }).selectOption('block')
  await expect(page.getByRole('listitem', { name: 'Rule 2' })).toContainText('Every other file')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/profile-rules-mobile.png', fullPage: true })
  await page.setViewportSize({ width: 1280, height: 900 })
  await page.getByRole('button', { name: 'Review rules' }).click()
  await expect(page.getByRole('dialog').getByRole('row').nth(1)).toHaveText('1Larger than 100 MBBlock')
  await page.getByRole('button', { name: 'Save rules' }).click()
  await expect(page.getByText('Rules saved.')).toBeVisible()
  // The fresh read after the save already shows the stored list.
  await expect(rows).toHaveCount(3)
  await expect(rows.nth(1)).toHaveText('1Larger than 100 MBBlock')
  await page.screenshot({ path: '../artifacts/console-e2e/profile-rules-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Edit rules' }).click()
  await page.getByRole('button', { name: 'Remove rule 1' }).click()
  await page.getByRole('button', { name: 'Review rules' }).click()
  await page.getByRole('button', { name: 'Save rules' }).click()
  await expect(rows).toHaveCount(2)
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
})

test('admin creates, renames, switches and deletes named profiles inside the client dialog', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Scan profiles' }).click()
  const original = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Acceptance routing', exact: true }) })
  await expect(original.getByRole('button', { name: 'Delete profile' })).toBeDisabled()
  await page.getByRole('button', { name: 'Add profile' }).click()
  await page.getByLabel('Profile name').fill('Light inspection')
  await page.locator('form').getByRole('checkbox', { name: /Static Metadata/ }).check()
  await page.getByRole('combobox', { name: 'When the result is not conclusive' }).selectOption('allow')
  await page.getByRole('button', { name: 'Review profile', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Its one rule sends every file to Static Metadata')
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  const created = page.getByText('Profile created.')
  await expect(created).toBeVisible()
  await page.getByRole('tab', { name: 'Connection' }).click()
  await page.getByRole('tab', { name: 'Scan profiles' }).click()
  await expect(created).toBeVisible()
  let named = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Light inspection', exact: true }) })
  await expect(named.getByRole('region', { name: 'Rules for Light inspection' })).toContainText('Allow, labelled Not fully scanned')
  await named.getByRole('button', { name: 'Rename or disable' }).click()
  await page.getByLabel('Profile name').fill('Fast inspection')
  await page.getByRole('button', { name: 'Review profile', exact: true }).click()
  await expect(page.getByRole('dialog')).toContainText('Rename Light inspection to Fast inspection')
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(page.getByText('Profile saved.')).toBeVisible()
  named = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Fast inspection', exact: true }) })
  await named.getByRole('button', { name: 'Make default' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(page.getByText('Default profile changed.')).toBeVisible()
  await expect(named.getByRole('button', { name: 'Delete profile' })).toBeDisabled()
  await expect(named.getByText(/Default profile/)).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../artifacts/console-e2e/named-profiles-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/named-profiles-mobile.png', fullPage: true })
  await original.getByRole('button', { name: 'Make default' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(original.getByText(/Default profile/)).toBeVisible()
  await named.getByRole('button', { name: 'Delete profile' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(named).toBeVisible()
  await named.getByRole('button', { name: 'Delete profile' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(page.getByText('Profile deleted.')).toBeVisible()
  await expect(named).toHaveCount(0)
  await expect(original.getByText(/Default profile/)).toBeVisible()
})
