import { test, expect } from '@playwright/test'

test('admin reviews fenced routing and analyst is denied', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Profile routing' }).click()
  await expect(page.getByRole('heading', { name: 'Acceptance routing' })).toBeVisible()
  const checkbox = page.getByRole('checkbox', { name: /Static Metadata/ })
  await checkbox.uncheck()
  await expect(page.getByRole('button', { name: 'Review engine routing' })).toBeDisabled()
  await checkbox.check()
  await page.getByRole('button', { name: 'Review engine routing' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect((await checkbox.boundingBox())!.width).toBeLessThanOrEqual(20)
  await page.screenshot({ path: '../artifacts/console-e2e/client-profiles-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Review engine routing' }).click()
  await page.getByRole('button', { name: 'Confirm engine routing' }).click()
  await expect(page.getByText('Profile routing saved. Refresh before editing again.')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Profile routing' }).click()
  await expect(checkbox).toBeChecked()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
})

test('admin creates, renames, switches and deletes named profiles inside the client dialog', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Profile routing' }).click()
  const original = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Acceptance routing', exact: true }) })
  await expect(original.getByRole('button', { name: 'Delete profile' })).toBeDisabled()
  await page.getByRole('button', { name: 'Add profile' }).click()
  await page.getByLabel('Profile name').fill('Light inspection')
  await page.locator('form').getByRole('checkbox', { name: /Static Metadata/ }).check()
  await page.getByRole('button', { name: 'Review profile', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  const saved = page.getByText('Profile change saved. Refresh before editing again.')
  await expect(saved).toBeVisible()
  await page.getByRole('tab', { name: 'Connection' }).click()
  await page.getByRole('tab', { name: 'Profile routing' }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh profiles' }).click()
  let named = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Light inspection', exact: true }) })
  await named.getByRole('button', { name: 'Edit profile' }).click()
  await page.getByLabel('Profile name').fill('Fast inspection')
  await page.getByRole('button', { name: 'Review profile', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh profiles' }).click()
  named = page.locator('article.client-profile').filter({ has: page.getByRole('heading', { name: 'Fast inspection', exact: true }) })
  await named.getByRole('button', { name: 'Make default' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh profiles' }).click()
  await expect(named.getByRole('button', { name: 'Delete profile' })).toBeDisabled()
  await expect(named.getByText(/Default profile/)).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../artifacts/console-e2e/named-profiles-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/named-profiles-mobile.png', fullPage: true })
  await original.getByRole('button', { name: 'Make default' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh profiles' }).click()
  await named.getByRole('button', { name: 'Delete profile' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(named).toBeVisible()
  await named.getByRole('button', { name: 'Delete profile' }).click()
  await page.getByRole('button', { name: 'Confirm profile change', exact: true }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh profiles' }).click()
  await expect(named).toHaveCount(0)
  await expect(original.getByText(/Default profile/)).toBeVisible()
})
