import { test, expect } from '@playwright/test'

test('admin scopes storage in the client dialog, denies all and restores deployment grants', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.getByRole('tab', { name: 'Storage', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Storage access', exact: true })).toBeVisible()
  await expect(page.locator('body')).not.toContainText('unmounted-private-root')
  await page.getByLabel('Access source').selectOption('custom')
  await page.getByLabel('Allowed prefixes for shared').fill('incoming/restricted/')
  await page.getByRole('combobox', { name: 'Access for archive', exact: true }).selectOption('all')
  await page.getByRole('button', { name: 'Review storage access' }).click()
  await expect(page.locator('#client-tab-setup')).toBeDisabled()
  const confirmation = page.getByRole('dialog', { name: 'Update storage access?' })
  await expect(confirmation).toContainText('incoming/restricted/')
  await expect(confirmation).toContainText('Entire backend')
  await confirmation.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Review storage access' }).click()
  await page.getByRole('button', { name: 'Confirm storage access' }).click()
  const saved = page.getByText('Storage access saved. Refresh before editing again.')
  await expect(saved).toBeVisible()
  await page.getByRole('tab', { name: 'Connection' }).click()
  await page.getByRole('tab', { name: 'Storage', exact: true }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh storage access' }).click()
  await expect(page.getByLabel('Access source')).toHaveValue('custom')
  await expect(page.getByLabel('Allowed prefixes for shared')).toHaveValue('incoming/restricted/')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: '../artifacts/console-e2e/client-storage-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/client-storage-mobile.png', fullPage: true })
  await page.getByRole('combobox', { name: 'Access for archive', exact: true }).selectOption('none')
  await page.getByRole('combobox', { name: 'Access for shared', exact: true }).selectOption('none')
  await page.getByRole('button', { name: 'Review storage access' }).click()
  await expect(confirmation).toContainText('No backend access is granted.')
  await page.getByRole('button', { name: 'Confirm storage access' }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh storage access' }).click()
  await expect(page.getByText('No backend access is granted.')).toBeVisible()
  await page.getByLabel('Access source').selectOption('environment')
  await page.getByRole('button', { name: 'Review storage access' }).click()
  await expect(confirmation).toContainText('incoming/client-a/')
  await page.getByRole('button', { name: 'Confirm storage access' }).click()
  await expect(saved).toBeVisible()
  await page.getByRole('button', { name: 'Refresh storage access' }).click()
  await expect(page.getByLabel('Access source')).toHaveValue('environment')
})

test('analyst cannot open storage administration', async ({ page }) => {
  await page.goto('service-clients/1/storage')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
})
