import { test, expect } from '@playwright/test'

test('analyst dashboard pagination, URL history, filters, mobile navigation and admin boundary', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('dashboard')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await expect(page.locator('tbody tr')).toHaveCount(20)
  await expect(page.getByRole('link', { name: 'acceptance-24.bin' })).toHaveAttribute('href', '/console/scans/25')
  await expect(page.getByText('0 / 100 · info')).toBeVisible()
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Older scans' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(5)
  await expect(page.getByRole('button', { name: 'Older scans' })).toBeDisabled()
  await page.goBack()
  await expect(page.locator('tbody tr')).toHaveCount(20)
  await page.getByLabel('Search scans').fill('acceptance-24')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.reload()
  await expect(page.getByLabel('Search scans')).toHaveValue('acceptance-24')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('navigation', { name: 'Workspace' }).getByRole('link', { name: 'Dashboard' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Engines', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-mobile.png', fullPage: true })
  const inventory = await page.request.get('/api/ui/v1/engines')
  expect(inventory.status()).toBe(403)
  await page.goto('engines')
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/dashboard/scans')).status()).toBe(401)
  expect(errors).toEqual([])
})
