import { test, expect } from '@playwright/test'

test('analyst dashboard pagination, URL history, filters, mobile navigation and admin boundary', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.addInitScript(() => { if (!localStorage.getItem('masp-console-theme')) localStorage.setItem('masp-console-theme', 'dark') })
  await page.goto('dashboard')
  await expect(page.getByRole('button', { name: 'Switch to light theme' })).toBeVisible()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await expect(page.locator('tbody tr')).toHaveCount(20)
  await expect(page.locator('.history-table-wrap')).toHaveCSS('background-color', 'rgb(255, 255, 255)')
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-light.png', fullPage: true })
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')
  await page.getByRole('button', { name: 'Switch to dark theme' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.getByRole('link', { name: 'acceptance-24.bin' })).toHaveAttribute('href', '/console/scans/25')
  const failedRow = page.getByRole('link', { name: 'acceptance-24.bin' }).locator('xpath=ancestor::tr')
  const risk = failedRow.locator('.risk-badge')
  await expect(risk).toContainText('info')
  await expect(risk).toContainText('0 / 100')
  // A zero-score failed scan must not be styled as a detection.
  await expect(risk).not.toHaveClass(/risk-badge-alert/)
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Older scans' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(5)
  await expect(page.getByRole('button', { name: 'Older scans' })).toBeDisabled()
  await page.goBack()
  await expect(page.locator('tbody tr')).toHaveCount(20)
  await page.getByLabel('Search scans').fill('acceptance-24')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.reload()
  await expect(page.getByLabel('Search scans')).toHaveValue('acceptance-24')
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('navigation', { name: 'Workspace' }).getByRole('link', { name: 'Dashboard' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Engines', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-mobile.png', fullPage: true })
  const inventory = await page.request.get('/api/ui/v1/engines')
  expect(inventory.status()).toBe(403)
  await page.goto('engines')
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/dashboard/scans')).status()).toBe(401)
  expect(errors).toEqual([])
})

test('admin bulk deletion is confirmed and reconciled against history', async ({ page }) => {
  await page.goto('dashboard')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: 'Select scan 23' })).toBeVisible()
  const checkbox = await page.getByRole('checkbox', { name: 'Select scan 23' }).boundingBox()
  expect(checkbox!.width).toBeLessThanOrEqual(20)
  expect(checkbox!.height).toBeLessThanOrEqual(20)
  expect(await page.getByLabel('Search scans').evaluate(element => parseFloat(getComputedStyle(element).paddingLeft))).toBeGreaterThanOrEqual(39)
  expect((await page.getByRole('columnheader', { name: 'Select all on this page' }).boundingBox())!.width).toBeLessThan(100)
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-admin-desktop.png', fullPage: true })
  await page.getByLabel('Search scans').fill('acceptance-22')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await page.setViewportSize({ width: 390, height: 844 })
  expect((await page.getByRole('checkbox', { name: 'Select scan 23' }).boundingBox())!.height).toBeLessThanOrEqual(20)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/dashboard-admin-mobile.png', fullPage: true })
  await page.getByRole('checkbox', { name: 'Select scan 23' }).check()
  await page.getByRole('button', { name: 'Delete selected (1)' }).click()
  await expect(page.getByRole('dialog')).toContainText('checked again before deletion')
  const deletion = page.waitForResponse(response => response.url().endsWith('/api/ui/v1/scans') && response.request().method() === 'DELETE')
  await page.getByRole('button', { name: 'Confirm deletion' }).click()
  expect((await deletion).status()).toBe(200)
  await expect(page.getByRole('status')).toContainText('Deleted 1 of 1 selected scans')
  await expect(page.locator('tbody tr')).toHaveCount(0)
  await page.getByRole('button', { name: 'Sign out' }).click()
})
