import { test, expect } from '@playwright/test'

test('session, explicit engine setup, worker check, edit, disable and delete', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('engines')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Engine deployments' })).toBeVisible()
  await page.getByRole('button', { name: 'Add engine' }).click()
  await expect(page.getByLabel('Deployment name')).toHaveCount(0)
  await page.getByRole('button', { name: 'ClamAV supported' }).click()
  await expect(page.getByLabel('Connection mode')).toHaveValue('')
  await page.getByLabel('Deployment name').fill('ClamAV browser acceptance')
  await page.getByLabel('Connection mode').selectOption('clamd')
  await page.getByLabel('clamd host', { exact: true }).fill('127.0.0.1')
  await page.getByLabel('clamd port', { exact: true }).fill('3310')
  await page.getByLabel('timeout seconds', { exact: true }).fill('60')
  await page.getByLabel('max file size bytes', { exact: true }).fill('52428800')
  await page.getByRole('button', { name: 'Create deployment' }).click()
  const card = page.locator('article').filter({ hasText: 'ClamAV browser acceptance' })
  await expect(card).toBeVisible()
  await card.getByRole('button', { name: 'Test connection' }).click()
  await expect(page.getByRole('alert')).toContainText('No active worker')
  await expect(card.locator('.health-pill')).toHaveText('unavailable')
  await card.getByRole('button', { name: 'Settings for ClamAV browser acceptance' }).click()
  await page.getByLabel('timeout seconds', { exact: true }).fill('75')
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await card.getByRole('button', { name: 'Disable', exact: true }).click()
  await expect(card.locator('.health-pill')).toHaveText('disabled')
  await expect(card.getByRole('button', { name: 'Test connection' })).toBeDisabled()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '../artifacts/console-e2e/engines-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: '../artifacts/console-e2e/engines-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await card.getByRole('button', { name: 'Remove ClamAV browser acceptance' }).click()
  await page.getByRole('button', { name: 'Remove deployment', exact: true }).click()
  await expect(card).toHaveCount(0)
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
