import { test, expect } from '@playwright/test'

test('admin creates, edits and deletes a pool; analyst is denied', async ({ page }) => {
  await page.goto('system/pools')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const create = page.getByRole('form', { name: 'Create worker pool' })
  await create.getByLabel('Pool name').fill('Acceptance pool')
  await create.getByLabel('Label selector').fill('site=lab')
  await create.getByRole('button', { name: 'Create pool' }).click()
  await page.getByRole('button', { name: 'Confirm pool change' }).click()
  await expect(page.getByRole('status')).toContainText('Created pool')
  const card = page.getByRole('article').filter({ has: page.getByRole('heading', { name: 'Acceptance pool' }) })
  await card.getByLabel('Pool state').selectOption('disabled')
  await card.getByRole('button', { name: 'Save pool' }).click()
  await page.getByRole('button', { name: 'Confirm pool change' }).click()
  await expect(page.getByRole('status')).toContainText('Updated pool')
  await page.reload()
  await expect(card.getByLabel('Pool state')).toHaveValue('disabled')
  await page.screenshot({ path: '../artifacts/console-e2e/pools-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/pools-mobile.png', fullPage: true })
  await card.getByRole('button', { name: 'Delete pool' }).click()
  await page.getByRole('button', { name: 'Confirm pool change' }).click()
  await expect(page.getByRole('status')).toContainText('Deleted pool')
  await expect(card).toHaveCount(0)
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/system/pools')).status()).toBe(403)
})
