import { test, expect } from '@playwright/test'

test('admin confirms expired sample deletion; analyst is denied', async ({ page }) => {
  await page.goto('system/retention')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByText('retention-expired.txt')).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Review deletion' }).click()
  await page.screenshot({ path: '../artifacts/console-e2e/retention-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(page.getByText('retention-expired.txt')).toBeVisible()
  await page.getByRole('button', { name: 'Review deletion' }).click()
  await page.getByRole('button', { name: 'Confirm retention deletion' }).click()
  await expect(page.getByText('File cleanup failed for deleted IDs: None')).toBeVisible()
  await page.getByRole('button', { name: 'Refresh preview' }).click()
  await expect(page.getByText('No expired inactive records on this page.')).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/system/retention')).status()).toBe(403)
})
