import { test, expect } from '@playwright/test'

test('admin browses runtime and active queue; analyst is denied', async ({ page }) => {
  await page.goto('system/runtime')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Runtime and active queue' })).toBeVisible()
  const queue = page.getByRole('region', { name: 'Active queue table' })
  await expect(queue.locator('tbody tr')).toHaveCount(20)
  await expect(page.getByRole('region', { name: 'Worker runtime table' })).toContainText('Acceptance worker')
  await page.getByRole('button', { name: 'Next scans' }).click()
  await expect(page).toHaveURL(/after=/)
  await page.reload()
  await expect(queue.locator('tbody tr').first()).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/runtime-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/system/queue')).status()).toBe(403)
})
