import { test, expect } from '@playwright/test'

test('admin saves and clears system limits; analyst is denied', async ({ page }) => {
  await page.goto('scan-policy')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'System limits & notifications' })).toBeVisible()
  const wait = page.getByLabel('API wait for a result (seconds)', { exact: true })
  const retry = page.getByLabel('API poll interval (seconds)', { exact: true })
  const upload = page.getByLabel('Largest upload (MiB)', { exact: true })
  const siem = page.getByRole('combobox', { name: 'Send not-allowed files to SIEM', exact: true })
  await wait.fill('30'); await retry.fill('3'); await upload.fill('1'); await siem.selectOption('1')
  await page.getByRole('button', { name: 'Review changes' }).click()
  await expect(page.getByRole('dialog')).toContainText('1.0 MiB')
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(wait).toHaveValue('30')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/scan-policy-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Review changes' }).click()
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByText('Settings saved. The values below are the ones now in effect.')).toBeVisible()
  // The fresh read after a save already shows the stored values.
  await expect(wait).toHaveValue('30'); await expect(retry).toHaveValue('3'); await expect(upload).toHaveValue('1'); await expect(siem).toHaveValue('1')
  await page.reload()
  await expect(wait).toHaveValue('30'); await expect(upload).toHaveValue('1'); await expect(siem).toHaveValue('1')
  await wait.fill(''); await retry.fill(''); await upload.fill(''); await siem.selectOption('')
  await page.getByRole('button', { name: 'Review changes' }).click()
  await page.getByRole('button', { name: 'Save settings' }).click()
  await expect(page.getByText('Settings saved. The values below are the ones now in effect.')).toBeVisible()
  await expect(wait).toHaveValue(''); await expect(siem).toHaveValue('')
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/scan-policy')).status()).toBe(403)
})
