import { test, expect } from '@playwright/test'

test('admin saves and clears policy overrides; analyst is denied', async ({ page }) => {
  await page.goto('scan-policy')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  const wait = page.getByLabel('API max wait (seconds)', { exact: true })
  const retry = page.getByLabel('API retry-after (seconds)', { exact: true })
  const upload = page.getByLabel('Upload size cap (bytes)', { exact: true })
  await wait.fill('30'); await retry.fill('3'); await upload.fill('1048576')
  await page.getByRole('button', { name: 'Review policy changes' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(wait).toHaveValue('30')
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/scan-policy-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Review policy changes' }).click()
  await page.getByRole('button', { name: 'Confirm policy changes' }).click()
  await expect(page.getByText('Scan policy saved. Reload policy to see the effective values.')).toBeVisible()
  await page.reload()
  await expect(wait).toHaveValue('30'); await expect(retry).toHaveValue('3'); await expect(upload).toHaveValue('1048576')
  await wait.fill(''); await retry.fill(''); await upload.fill('')
  await page.getByRole('button', { name: 'Review policy changes' }).click()
  await page.getByRole('button', { name: 'Confirm policy changes' }).click()
  await expect(page.getByText('Scan policy saved. Reload policy to see the effective values.')).toBeVisible()
  await page.getByRole('button', { name: 'Reload policy' }).click()
  await expect(wait).toHaveValue('')
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/scan-policy')).status()).toBe(403)
})
