import { test, expect } from '@playwright/test'

test('admin updates client state and analyst is denied', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Manage Acceptance integration' })).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 960 })
  for (const theme of ['light', 'dark']) {
    const toggle = page.getByRole('button', { name: `Switch to ${theme} theme` })
    if (await toggle.count()) await toggle.click()
    await page.screenshot({ path: `../artifacts/console-e2e/service-clients-${theme}.png`, fullPage: true, animations: 'disabled' })
  }
  await page.getByRole('button', { name: 'Manage Acceptance integration' }).click()
  await page.screenshot({ path: '../artifacts/console-e2e/client-settings-dialog.png', animations: 'disabled' })
  await page.getByLabel('Display name').fill('Updated integration')
  await page.getByLabel('Client state').selectOption('disabled')
  await page.getByRole('button', { name: 'Review client changes' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Review client changes' }).click()
  await page.getByRole('button', { name: 'Confirm client changes' }).click()
  await expect(page.getByText('Service client updated. Close this window and refresh clients to see the current state.')).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Manage Updated integration' }).click()
  await expect(page.getByLabel('Client state')).toHaveValue('disabled')
  await expect(page.getByRole('heading', { name: 'Updated integration' })).toBeVisible()
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Switch to light theme' }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/service-clients-mobile.png', fullPage: true, animations: 'disabled' })
  await page.getByRole('button', { name: 'Manage Updated integration' }).click()
  await page.screenshot({ path: '../artifacts/console-e2e/client-settings-dialog-mobile.png', animations: 'disabled' })
  await page.getByRole('button', { name: 'Close dialog' }).click()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/service-clients')).status()).toBe(403)
})
