import { test, expect } from '@playwright/test'

test('admin updates client state and analyst is denied', async ({ page }) => {
  await page.goto('service-clients')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Acceptance integration' })).toBeVisible()
  await page.getByLabel('Display name').fill('Updated integration')
  await page.getByLabel('Client state').selectOption('disabled')
  await page.getByRole('button', { name: 'Review client changes' }).click()
  await page.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Review client changes' }).click()
  await page.getByRole('button', { name: 'Confirm client changes' }).click()
  await expect(page.getByText('Service client updated. Refresh clients to see the current state.')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Client state')).toHaveValue('disabled')
  await expect(page.getByRole('heading', { name: 'Updated integration' })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/service-clients-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/service-clients')).status()).toBe(403)
})
