import { test, expect } from '@playwright/test'

test('analyst sends a benign file and sees accepted scan in manual history', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('scans/new')
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Submit sample', exact: true })).toBeVisible()
  await page.getByLabel('Sample file').setInputFiles({ name: 'browser-benign.txt', mimeType: 'text/plain', buffer: Buffer.from('Benign browser acceptance fixture. No executable content.') })
  await page.getByLabel('Case name').fill('IR-browser-upload')
  await page.getByLabel('Priority').selectOption('High')
  await page.getByLabel('Analyst note').fill('Synthetic data in a disposable database.')
  await page.screenshot({ path: '../artifacts/console-e2e/submission-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/submission-mobile.png', fullPage: true })
  const submitted = page.waitForResponse(response => response.url().endsWith('/api/ui/v1/scans') && response.request().method() === 'POST')
  await page.getByRole('button', { name: 'Create scan' }).click()
  expect((await submitted).status()).toBe(202)
  await expect(page.getByRole('heading', { name: 'Scan accepted' })).toBeVisible()
  await expect(page.getByText(/not a completed scan or a clean verdict/)).toBeVisible()
  const report = await page.getByRole('link', { name: 'Open scan report' }).getAttribute('href')
  expect(report).toMatch(/^\/console\/scans\/\d+$/)
  await page.getByRole('navigation', { name: 'Workspace' }).getByRole('link', { name: 'Dashboard', exact: true }).click()
  await page.getByLabel('Search scans').fill('IR-browser-upload')
  await page.getByRole('button', { name: 'Apply filters' }).click()
  await expect(page.locator('tbody tr')).toHaveCount(1)
  await expect(page.getByRole('link', { name: 'browser-benign.txt' })).toHaveAttribute('href', report!)
  await expect(page.locator('tbody')).toContainText('queued')
  await expect(page.locator('tbody')).toContainText('Pending')
  expect(errors).toEqual([])
})
