import { test, expect } from '@playwright/test'

test('admin manages worker lifecycle and revocation; analyst cannot access System', async ({ page }) => {
  await page.goto('system')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Managed worker nodes' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Acceptance worker' })).toBeVisible()
  await page.getByLabel('Lifecycle for console-node').selectOption('draining')
  await page.getByRole('button', { name: 'Apply lifecycle' }).click()
  await expect(page.getByRole('dialog')).toContainText('owned work finishes')
  await page.getByRole('button', { name: 'Confirm worker action' }).click()
  await expect(page.getByRole('status')).toContainText('changed to draining')
  await page.reload()
  await expect(page.locator('dd').filter({ hasText: /^draining$/ })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/system-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Revoke agent credentials' }).click()
  await expect(page.getByRole('dialog')).toContainText('Running Control API work loses authorization')
  await page.getByRole('button', { name: 'Confirm worker action' }).click()
  await expect(page.getByRole('status')).toContainText('Revoked 1 agent credential')
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  expect((await page.request.get('/api/ui/v1/system/workers')).status()).toBe(403)
  await expect(page.getByRole('navigation', { name: 'Workspace' }).getByRole('link', { name: 'System' })).toHaveCount(0)
})
