import { test, expect } from '@playwright/test'

test('admin creates a local analyst who can sign in without admin access', async ({ page }) => {
  await page.goto('users')
  await page.getByLabel('Username', { exact: true }).fill('console-admin')
  await page.getByLabel('Password', { exact: true }).fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('form', { name: 'Create local user' }).getByLabel('Username', { exact: true }).fill('created-analyst')
  await page.getByLabel('Initial password').fill('created-test-only')
  await page.getByRole('button', { name: 'Review new user' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Confirm creation' }).click()
  await expect(page.getByRole('status')).toContainText('created')
  await expect(page.getByLabel('Initial password')).toHaveValue('')
  await page.getByRole('button', { name: 'Refresh users' }).click()
  await expect(page.getByRole('heading', { name: 'created-analyst', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Sign out' }).click()
  await expect(page.getByRole('heading', { name: 'Welcome back.' })).toBeVisible()
  await page.getByLabel('Username', { exact: true }).fill('created-analyst')
  await page.getByLabel('Password', { exact: true }).fill('created-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Users', exact: true })).toHaveCount(0)
  await page.getByRole('link', { name: 'Dashboard', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Dashboard', exact: true })).toBeVisible()
})
