import { test, expect } from '@playwright/test'

test('create client, add and revoke credentials without displaying secrets', async ({ page }) => {
  await page.goto('service-clients/new')
  await page.getByLabel('Username').fill('console-admin')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByLabel('Client key').fill('credential-acceptance')
  await page.getByLabel('Display name').fill('Credential acceptance')
  await page.getByLabel('Default profile name').fill('Default acceptance')
  await page.getByRole('checkbox', { name: /Static Metadata/ }).check()
  await page.getByLabel('Credential label').fill('Initial acceptance')
  const token = 'synthetic-acceptance-token-xxxxxxxxxxxxxxxxxxxxxxxx'
  await page.getByLabel('API token').fill(token)
  await page.getByRole('button', { name: 'Review client creation' }).click()
  await expect(page.getByRole('dialog')).not.toContainText(token)
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await page.getByRole('link', { name: 'Manage created client credentials' }).click()
  await expect(page.getByRole('heading', { name: 'Initial acceptance' })).toBeVisible()
  await page.getByLabel('Credential label').fill('Rotation acceptance')
  await page.getByLabel('API token').fill(token + '-rotation')
  await page.getByRole('button', { name: 'Review credential', exact: true }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByLabel('API token')).toHaveValue('')
  await page.getByRole('button', { name: 'Refresh credentials' }).click()
  const card = page.locator('article').filter({ has: page.getByRole('heading', { name: 'Initial acceptance' }) })
  await card.getByRole('button', { name: /Revoke credential/ }).click()
  await page.getByRole('button', { name: 'Confirm', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Credential revoked')
  await page.reload()
  await expect(card).toContainText('Revoked')
  await expect(card.getByRole('button')).toBeDisabled()
  await expect(page.locator('body')).not.toContainText(token)
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: '../artifacts/console-e2e/credentials-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Sign out' }).click()
  await page.getByLabel('Username').fill('console-analyst')
  await page.getByLabel('Password').fill('console-test-only')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Administrator access required' })).toBeVisible()
})
